# Base layer based on Linux Debian Bookworm
FROM python:3.10-slim-bookworm

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the project into the image
ADD . /app

# Sync the project into a new environment, using the frozen lockfile
WORKDIR /app
RUN uv sync --frozen

# Run our service
CMD ["uv", "run", "python", "run.py"]
