[project]
name = "candles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "loguru>=0.7.2",
    "pydantic-settings>=2.6.1",
    "quixstreams>=3.4.0",
]
